WebAppAdmin/WebApp/Models/COACH_STANDARD.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COACH_STANDARD
    {
        public decimal TRAINID { get; set; }
        public decimal COACHNO { get; set; }
        public decimal WINDOWSEATS { get; set; }
        public decimal AISLESEATS { get; set; }
        public decimal TABLESEATS { get; set; }
    
        public virtual TRAIN TRAIN { get; set; }
    }
}

WebAppAdmin/WebApp/Controllers/Coach_StandardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class Coach_StandardController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Coach_Standard
        public ActionResult Index(string searchBy, string search)
        {
            var cOACH_STANDARD = db.COACH_STANDARD.Include(c => c.TRAIN);

            if (searchBy == "CoachNO")
            {
                return View(db.COACH_STANDARD.Where(c => c.COACHNO.ToString().Contains(search) || search == null).ToList());
            }
            else
            {
                return View(db.COACH_STANDARD.ToList());
            }
        }

        // GET: Coach_Standard/Details/5
        public ActionResult Details(decimal id, decimal idcoach)
        {
            if (id == null && idcoach == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COACH_STANDARD cOACH_STANDARD = db.COACH_STANDARD.Find(id, idcoach);
            if (cOACH_STANDARD == null)
            {
                return HttpNotFound();
            }
            return View(cOACH_STANDARD);
        }

        // GET: Coach_Standard/Create
        public ActionResult Create()
        {
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID");
            return View();
        }

        // POST: Coach_Standard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TRAINID,COACHNO,WINDOWSEATS,AISLESEATS,TABLESEATS")] COACH_STANDARD cOACH_STANDARD)
        {
            if (ModelState.IsValid)
            {
                db.COACH_STANDARD.Add(cOACH_STANDARD);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "STATUS", cOACH_STANDARD.TRAINID);
            return View(cOACH_STANDARD);
        }

        // GET: Coach_Standard/Edit/5
        public ActionResult Edit(decimal id, decimal idcoach)
        {
            if (id == null && idcoach == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COACH_STANDARD cOACH_STANDARD = db.COACH_STANDARD.Find(id, idcoach);
            if (cOACH_STANDARD == null)
            {
                return HttpNotFound();
            }
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID", cOACH_STANDARD.TRAINID);
            return View(cOACH_STANDARD);
        }

        // POST: Coach_Standard/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TRAINID,COACHNO,WINDOWSEATS,AISLESEATS,TABLESEATS")] COACH_STANDARD cOACH_STANDARD)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cOACH_STANDARD).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID", cOACH_STANDARD.TRAINID);
            return View(cOACH_STANDARD);
        }

        // GET: Coach_Standard/Delete/5
        public ActionResult Delete(decimal id, decimal idcoach)
        {
            if (id == null && idcoach == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            COACH_STANDARD cOACH_STANDARD = db.COACH_STANDARD.Find(id, idcoach);
            if (cOACH_STANDARD == null)
            {
                return HttpNotFound();
            }
            return View(cOACH_STANDARD);
        }

        // POST: Coach_Standard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id, decimal idcoach)
        {
            COACH_STANDARD cOACH_STANDARD = db.COACH_STANDARD.Find(id, idcoach);
            db.COACH_STANDARD.Remove(cOACH_STANDARD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppAdmin/WebApp/Views/Coach_Standard/Create.cshtml
@model WebApp.Models.COACH_STANDARD

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Title of the page-->
    <h2><i class="fas fa-user-plus"></i> Create Coach</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TRAINID, "TRAINID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TRAINID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TRAINID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.COACHNO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.COACHNO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.COACHNO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.WINDOWSEATS, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.WINDOWSEATS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.WINDOWSEATS, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AISLESEATS, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AISLESEATS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AISLESEATS, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TABLESEATS, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TABLESEATS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TABLESEATS, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
                <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-backward"></i> @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    }

</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppAdmin/WebApp/Views/Coach_Standard/Delete.cshtml
@model WebApp.Models.COACH_STANDARD

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Delete page title-->
    <h2><i class="fas fa-trash-alt"></i> Delete Coach</h2>

    <!--make sure the uiser wants to delete the following coach-->
    <h3>Are you sure you want to delete this Coach?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Coach Number:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.COACHNO)
            </dd>
            <dt>
                Window Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WINDOWSEATS)
            </dd>

            <dt>
                Aisle Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AISLESEATS)
            </dd>

            <dt>
                Table Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TABLESEATS)
            </dd>


        </dl>

        @using (Html.BeginForm())
        {
            <!--security feature-->
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> <!--delete button-->
                <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--back to list button-->
                </p>
            </div>
        }
    </div>
</body>

WebAppAdmin/WebApp/Views/Coach_Standard/Details.cshtml
@model WebApp.Models.COACH_STANDARD

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->

    <h2><i class="fas fa-info-circle"></i> Coach Details</h2>

    <!--list of each attributes label and value-->
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Train ID:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TRAINID)
            </dd>
            <dt>
                COach Number:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.COACHNO)
            </dd>
            <dt>
                Window Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WINDOWSEATS)
            </dd>

            <dt>
                Aisle Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AISLESEATS)
            </dd>

            <dt>
                Table Seats:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TABLESEATS)
            </dd>

            <dt>
                Train Status:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TRAIN.STATUS)
            </dd>

        </dl>
        <!--container with edit and back to list button-->
        <div class="form-group">
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = Model.TRAINID, idcoach = Model.COACHNO })
            </p>
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </div>
</body>

WebAppAdmin/WebApp/Views/Coach_Standard/Edit.cshtml
@model WebApp.Models.COACH_STANDARD

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->
    <h2><i class="fas fa-edit"></i> Edit Coach</h2>

    <!--Creating a form with the user details-->
    @using (Html.BeginForm())
    {
        <!--the AntiForgeryToken for security-->
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TRAINID)

        @Html.HiddenFor(model => model.COACHNO)

        <div class="form-group">
            @Html.LabelFor(model => model.WINDOWSEATS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WINDOWSEATS, new { htmlAttributes = new { @class = "form-control" } }) <!--The value of window seats-->
                @Html.ValidationMessageFor(model => model.WINDOWSEATS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AISLESEATS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AISLESEATS, new { htmlAttributes = new { @class = "form-control" } }) <!--The value ofaisle seats-->
                @Html.ValidationMessageFor(model => model.AISLESEATS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TABLESEATS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TABLESEATS, new { htmlAttributes = new { @class = "form-control" } }) <!--The value of table seats-->
                @Html.ValidationMessageFor(model => model.TABLESEATS, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--Container with the Save and Back to list button-->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" /> <!--Save button-->
            </div>
            <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--Button to go back to list-->
            </div>
        </div>
    </div>
    }
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppAdmin/WebApp/Views/Coach_Standard/Index.cshtml
@model IEnumerable<WebApp.Models.COACH_STANDARD>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a journey icon-->
    <h2><i class="fas fa-train"></i> Coach Standard</h2>

    <!--The search bar searching for coach number id  of the coaches the list on button click-->
    <p style="margin-top:20px">
        @using (@Html.BeginForm("Index", "Coach_Standard", FormMethod.Get))
        {
            <b><i class="fas fa-search"></i> Search By:</b>
            @Html.RadioButton("searchBy", "CoachNO", true) <text>Coach Number</text>
            @Html.TextBox("Search") <input type="submit" value="Search">
        }
    </p>

    <!--Create new user button which leads to the Create view of the coach first with the appropriate design-->
    <a>
        <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-bottom:20px;
                  margin:10px;
                  width: auto;
                  height: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
            <i class="fas fa-plus"></i> @Html.ActionLink("Create New", "Create")
        </p>
    </a>

    <!--Table where fields of the coach labels are shown-->
    <table class="table">
        <tr>
            <th>
                Train ID <!--train id -->
            </th>
            <th>
                Coach Number <!--coach id -->
            </th>
            <th>
                Window Seats <!--window seats -->
            </th>
            <th>
                Aisle Seats <!--aisle seats -->
            </th>
            <th>
                Table Seats <!--table seats -->
            </th>
            <th>
                Train Status <!--train status -->
            </th>
            <th></th>
        </tr>

        <!--For each field in the table for the coach first details then the specific data are passed into the table-->
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TRAINID) <!--train id name id will be displayed under the  train id field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.COACHNO) <!--coach id name id will be displayed under the  coach id field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WINDOWSEATS) <!--window seats name id will be displayed under the  window seats field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AISLESEATS) <!--aisle seats id name id will be displayed under the  aisle seats id field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TABLESEATS) <!--table seats name id will be displayed under the table seats field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TRAIN.STATUS) <!--train status id name id will be displayed under the  train status id field-->
            </td>
            <!--Edit, Details, Delete buttons at the end of the user details redirecting to their representative page-->
            <td>
                <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.TRAINID, idcoach = item.COACHNO }) |
                <i class="fas fa-info-circle"></i> @Html.ActionLink("Details", "Details", new { id = item.TRAINID, idcoach = item.COACHNO }) |
                <i class="fas fa-trash-alt"></i> @Html.ActionLink("Delete", "Delete", new { id = item.TRAINID, idcoach = item.COACHNO })
            </td>
        </tr>
        }

    </table>
</body>