WebAppAdmin/WebApp/Models/ROUTE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROUTE()
        {
            this.SCHEDULEs = new HashSet<SCHEDULE>();
        }
    
        public decimal ROUTEID { get; set; }
        public decimal DEPARTURE { get; set; }
        public Nullable<decimal> FIRSTSTOP { get; set; }
        public decimal DESTINATION { get; set; }
    
        public virtual STATION STATION { get; set; }
        public virtual STATION STATION1 { get; set; }
        public virtual STATION STATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULE> SCHEDULEs { get; set; }
    }
}

WebAppAdmin/WebApp/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class RoutesController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Routes
        public ActionResult Index(string searchBy, string search)
        { 
            var rOUTEs = db.ROUTEs.Include(r => r.STATION).Include(r => r.STATION1).Include(r => r.STATION2);

            if (searchBy == "Departure")
            {
                return View(db.ROUTEs.Where(r => r.STATION.STATIONNAME.Contains(search) || search == null).ToList());
            }
            else
            {
                return View(db.ROUTEs.ToList());
            }
        }

        // GET: Routes/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROUTE rOUTE = db.ROUTEs.Find(id);
            if (rOUTE == null)
            {
                return HttpNotFound();
            }
            return View(rOUTE);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {
            ViewBag.DEPARTURE = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME");
            ViewBag.DESTINATION = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME");
            ViewBag.FIRSTSTOP = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME");
            ROUTE newRoute = new ROUTE();

            var lastRoute = db.ROUTEs.OrderByDescending(x => x.ROUTEID).FirstOrDefault();

            if (lastRoute == null)
            {
                newRoute.ROUTEID = 5001;
            }
            else if (lastRoute.ROUTEID != 0)
            {
                newRoute.ROUTEID = lastRoute.ROUTEID + 1;
            }

            return View(newRoute);
        }

        // POST: Routes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ROUTEID,DEPARTURE,FIRSTSTOP,DESTINATION")] ROUTE rOUTE)
        {
            if (ModelState.IsValid)
            {
                db.ROUTEs.Add(rOUTE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DEPARTURE = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DEPARTURE);
            ViewBag.DESTINATION = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DESTINATION);
            ViewBag.FIRSTSTOP = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.FIRSTSTOP);
            return View(rOUTE);
        }

        // GET: Routes/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROUTE rOUTE = db.ROUTEs.Find(id);
            if (rOUTE == null)
            {
                return HttpNotFound();
            }
            ViewBag.DEPARTURE = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DEPARTURE);
            ViewBag.DESTINATION = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DESTINATION);
            ViewBag.FIRSTSTOP = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.FIRSTSTOP);
            return View(rOUTE);
        }

        // POST: Routes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ROUTEID,DEPARTURE,FIRSTSTOP,DESTINATION")] ROUTE rOUTE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rOUTE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DEPARTURE = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DEPARTURE);
            ViewBag.DESTINATION = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.DESTINATION);
            ViewBag.FIRSTSTOP = new SelectList(db.STATIONs, "STATIONID", "STATIONNAME", rOUTE.FIRSTSTOP);
            return View(rOUTE);
        }

        // GET: Routes/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ROUTE rOUTE = db.ROUTEs.Find(id);
            if (rOUTE == null)
            {
                return HttpNotFound();
            }
            return View(rOUTE);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            ROUTE rOUTE = db.ROUTEs.Find(id);
            db.ROUTEs.Remove(rOUTE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppAdmin/WebApp/Views/Routes/Create.cshtml
@model WebApp.Models.ROUTE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Title of the page-->
    <h2><i class="fas fa-plus"></i>Create Route</h2>


    @using (Html.BeginForm())
    {
        <!--security token-->
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ROUTEID, htmlAttributes: new { @class = "control-label col-md-2" }) <!--route id label-->
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ROUTEID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } }) <!--route id value-->
                    @Html.ValidationMessageFor(model => model.ROUTEID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DEPARTURE, "DEPARTURE", htmlAttributes: new { @class = "control-label col-md-2" }) <!--departure id label-->
                <div class="col-md-10">
                    @Html.DropDownList("DEPARTURE", null, htmlAttributes: new { @class = "form-control" }) <!--departure value-->
                    @Html.ValidationMessageFor(model => model.DEPARTURE, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FIRSTSTOP, "FIRSTSTOP", htmlAttributes: new { @class = "control-label col-md-2" }) <!--first stop label-->
                <div class="col-md-10">
                    @Html.DropDownList("FIRSTSTOP", null, htmlAttributes: new { @class = "form-control" }) <!--first stop value-->
                    
                    @Html.ValidationMessageFor(model => model.FIRSTSTOP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DESTINATION, "DESTINATION", htmlAttributes: new { @class = "control-label col-md-2" }) <!--destination label-->
                <div class="col-md-10">
                    @Html.DropDownList("DESTINATION", null, htmlAttributes: new { @class = "form-control" }) <!--destination value-->
                    @Html.ValidationMessageFor(model => model.DESTINATION, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" /> <!--create button-->
                </div>
                <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-backward"></i> @Html.ActionLink("Back to List", "Index") <!--back button-->
                </div>
            </div>
        </div>
    }
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppAdmin/WebApp/Views/Routes/Delete.cshtml
@model WebApp.Models.ROUTE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Delete page title-->
    <h2><i class="fas fa-trash-alt"></i> Delete Route</h2>

    <!--make sure the user wants to delete the following route-->
    <h3>Are you sure you want to delete this Route?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Departure:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION.STATIONNAME)
            </dd>

            <dt>
                First Stop:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION1.STATIONNAME)
            </dd>

            <dt>
                Destination:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION2.STATIONNAME)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            <!--security feature-->
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /><!--delete button-->
                <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--back to list button-->
                </p>
            </div>
        }
    </div>
</body>

WebAppAdmin/WebApp/Views/Routes/Details.cshtml
@model WebApp.Models.ROUTE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->
    <h2><i class="fas fa-info-circle"></i>Route Details</h2>

    <!--list of each attributes label and value-->
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Route ID:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ROUTEID)
            </dd>
            <dt>
                Departure:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION.STATIONNAME)
            </dd>

            <dt>
                First Stop:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION1.STATIONNAME)
            </dd>

            <dt>
                Destination:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.STATION2.STATIONNAME)
            </dd>

        </dl>
        <!--container with the edit button and back to list-->
        <div class="form-group">
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = Model.ROUTEID })
            </p>
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </div>
</body>

WebAppAdmin/WebApp/Views/Routes/Edit.cshtml
@model WebApp.Models.ROUTE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->
    <h2><i class="fas fa-edit"></i> Edit Route</h2>

    <!--Creating a form with the user details-->
    @using (Html.BeginForm())
    {
        <!--the AntiForgeryToken for security-->
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" }) <!--summarize error messages in a specific place-->
        @Html.HiddenFor(model => model.ROUTEID)  <!-- Route ID is unique so it can't be changed-->

        <div class="form-group">
            @Html.LabelFor(model => model.DEPARTURE, "DEPARTURE", htmlAttributes: new { @class = "control-label col-md-2" }) <!--The departure label-->
            <div class="col-md-10">
                @Html.DropDownList("DEPARTURE", null, htmlAttributes: new { @class = "form-control" }) <!--The value of departure-->
                @Html.ValidationMessageFor(model => model.DEPARTURE, "", new { @class = "text-danger" }) <!--Displaying an error in the context if exists-->
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIRSTSTOP, "FIRSTSTOP", htmlAttributes: new { @class = "control-label col-md-2" }) <!--The first stop label-->
            <div class="col-md-10">
                @Html.DropDownList("FIRSTSTOP", null, htmlAttributes: new { @class = "form-control" }) <!--The value of first stop-->
                @Html.ValidationMessageFor(model => model.FIRSTSTOP, "", new { @class = "text-danger" }) <!--Displaying an error in the context if exists-->
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESTINATION, "DESTINATION", htmlAttributes: new { @class = "control-label col-md-2" }) <!--The destination label-->
            <div class="col-md-10">
                @Html.DropDownList("DESTINATION", null, htmlAttributes: new { @class = "form-control" }) <!--The value of destination-->
                @Html.ValidationMessageFor(model => model.DESTINATION, "", new { @class = "text-danger" }) <!--Displaying an error in the context if exists-->
            </div>
        </div>

        <!--Container with the Save and Back to list button-->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" /> <!--Save button-->
            </div>
            <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--Button to go back to list-->
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppAdmin/WebApp/Views/Routes/Index.cshtml
@model IEnumerable<WebApp.Models.ROUTE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml"; // the layout of the page
}

<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a route icon-->
    <h2><i class="fas fa-route"></i> Routes</h2>

    <!--The search bar searching for Departure  of the routes on the list on button click-->
    <p>
        @using (@Html.BeginForm("Index", "Routes", FormMethod.Get))
        {
            <b><i class="fas fa-search"></i> Search By:</b>
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "Departure", true) <text>Departure</text>
            @Html.TextBox("Search") <input type="submit" value="search">
        }
    </p>

    <!--Create new user button which leads to the Create view of the journey with the appropriate design-->
    <a>
        <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-bottom:20px;
                  margin:10px;
                  width: auto;
                  height: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
            <i class="fas fa-plus"></i> @Html.ActionLink("Create New", "Create")
        </p>
    </a>

    <!--Table where fields of the user are shown-->
    <table class="table">
        <tr>
            <th>
                Departure <!--departure -->
            </th>
            <th>
                First Stop <!--first stop-->
            </th>
            <th>
                Destination <!--destinatuion-->
            </th>
            <th></th>
        </tr>

        <!--For each field in the table for the station then the specific data are passed into the table-->
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.STATION.STATIONNAME) <!--station namer id will be displayed under the  departure field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.STATION1.STATIONNAME) <!--station name will be displayed under the  station 1 field-->
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.STATION2.STATIONNAME) <!--station name id will be displayed under the  arrival id field-->
            </td>
            <!--Edit, Details, Delete buttons at the end of the user details redirecting to their representative page-->
            <td>
                <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.ROUTEID }) |
                <i class="fas fa-info-circle"></i> @Html.ActionLink("Details", "Details", new { id = item.ROUTEID }) |
                <i class="fas fa-trash-alt"></i> @Html.ActionLink("Delete", "Delete", new { id = item.ROUTEID })
            </td>
        </tr>
        }

    </table>
</body>