WebAppAdmin/WebApp/Models/SCHEDULE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public decimal ROUTEID { get; set; }
        public decimal TRAINID { get; set; }
        public System.DateTime DEPARTURETIME { get; set; }
        public System.DateTime ARRIVALTIME { get; set; }
    
        public virtual ROUTE ROUTE { get; set; }
        public virtual TRAIN TRAIN { get; set; }
    }
}

WebAppAdmin/WebApp/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SchedulesController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Schedules
        public ActionResult Index(string searchBy, string search)
        {
            var sCHEDULEs = db.SCHEDULEs.Include(s => s.ROUTE).Include(s => s.TRAIN);

            if (searchBy == "ROUTEID")
            {
                return View(db.SCHEDULEs.Where(s => s.ROUTEID.ToString().Contains(search) || search == null).ToList());
            }
            else
            {
                return View(sCHEDULEs.ToList());
            }
           
        }

        // GET: Schedules/Details/5
        public ActionResult Details(decimal id, decimal idsch)
        {
            if (id == null && idsch == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SCHEDULE sCHEDULE = db.SCHEDULEs.Find(id, idsch);
            if (sCHEDULE == null)
            {
                return HttpNotFound();
            }
            return View(sCHEDULE);
        }

        // GET: Schedules/Create
        public ActionResult Create()
        {
            ViewBag.ROUTEID = new SelectList(db.ROUTEs, "ROUTEID", "ROUTEID");
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID");
            return View();
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ROUTEID,TRAINID,DEPARTURETIME,ARRIVALTIME")] SCHEDULE sCHEDULE)
        {
            if (ModelState.IsValid)
            {
                db.SCHEDULEs.Add(sCHEDULE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ROUTEID = new SelectList(db.ROUTEs, "ROUTEID", "ROUTEID", sCHEDULE.ROUTEID);
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID", sCHEDULE.TRAINID);
            return View(sCHEDULE);
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(decimal id, decimal idsch)
        {
            if (id == null && idsch == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SCHEDULE sCHEDULE = db.SCHEDULEs.Find(id, idsch);
            if (sCHEDULE == null)
            {
                return HttpNotFound();
            }
            ViewBag.ROUTEID = new SelectList(db.ROUTEs, "ROUTEID", "ROUTEID", sCHEDULE.ROUTEID);
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID", sCHEDULE.TRAINID);
            return View(sCHEDULE);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ROUTEID,TRAINID,DEPARTURETIME,ARRIVALTIME")] SCHEDULE sCHEDULE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sCHEDULE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ROUTEID = new SelectList(db.ROUTEs, "ROUTEID", "ROUTEID", sCHEDULE.ROUTEID);
            ViewBag.TRAINID = new SelectList(db.TRAINs, "TRAINID", "TRAINID", sCHEDULE.TRAINID);
            return View(sCHEDULE);
        }

        // GET: Schedules/Delete/5
        public ActionResult Delete(decimal id, decimal idsch)
        {
            if (id == null && idsch == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SCHEDULE sCHEDULE = db.SCHEDULEs.Find(id, idsch);
            if (sCHEDULE == null)
            {
                return HttpNotFound();
            }
            return View(sCHEDULE);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id, decimal idsch)
        {
            SCHEDULE sCHEDULE = db.SCHEDULEs.Find(id, idsch);
            db.SCHEDULEs.Remove(sCHEDULE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppAdmin/WebApp/Views/Schedules/Create.cshtml
@model WebApp.Models.SCHEDULE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Title of the page-->
    <h2><i class="fas fa-plus"></i> Create Schedule</h2>


    @using (Html.BeginForm())
    {
        <!--security feature-->
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ROUTEID, "ROUTEID", htmlAttributes: new { @class = "control-label col-md-2" }) <!--route id label-->
                <div class="col-md-10">
                    @Html.DropDownList("ROUTEID", null, htmlAttributes: new { @class = "form-control" }) <!--route id dropdown-->
                    @Html.ValidationMessageFor(model => model.ROUTEID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TRAINID, "TRAINID", htmlAttributes: new { @class = "control-label col-md-2" }) <!--train id label-->
                <div class="col-md-10">
                    @Html.DropDownList("TRAINID", null, htmlAttributes: new { @class = "form-control" }) <!--train id dropdown-->
                    @Html.ValidationMessageFor(model => model.TRAINID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DEPARTURETIME, htmlAttributes: new { @class = "control-label col-md-2" }) <!--departure time label-->
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DEPARTURETIME, new { htmlAttributes = new { @class = "form-control" } }) <!--departure time value-->
                    @Html.ValidationMessageFor(model => model.DEPARTURETIME, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ARRIVALTIME, htmlAttributes: new { @class = "control-label col-md-2" }) <!--arrival time label-->
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ARRIVALTIME, new { htmlAttributes = new { @class = "form-control" } }) <!--arrival time value-->
                    @Html.ValidationMessageFor(model => model.ARRIVALTIME, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" /> <!--create button-->
                </div>
                <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-backward"></i> @Html.ActionLink("Back to List", "Index") <!--back to listbutton-->
                </div>
            </div>
        </div>
    }
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppAdmin/WebApp/Views/Schedules/Delete.cshtml
@model WebApp.Models.SCHEDULE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--Delete page title-->
    <h2><i class="fas fa-trash-alt"></i> Delete Schedule</h2>
     <!--Make sure the user wants to delete the schedule-->
    <h3>Are you sure you want to delete this Schedule?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Departure Time:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DEPARTURETIME)
            </dd>

            <dt>
                Arrival Time:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ARRIVALTIME)
            </dd>

            <dt>
                Route ID:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ROUTE.ROUTEID)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            <!--security feature-->
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> <!--delete button-->
                <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--back to list button-->
                </p>
            </div>
        }
    </div>
</body>

WebAppAdmin/WebApp/Views/Schedules/Details.cshtml
@model WebApp.Models.SCHEDULE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
}
<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->
    <h2><i class="fas fa-info-circle"></i> Schedule Details</h2>

    <!--list for each attributes label and their representative balue-->
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Train ID:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TRAINID)
            </dd>
            <dt>
                Route ID:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ROUTE.ROUTEID)
            </dd>
            <dt>
                Departure Time:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DEPARTURETIME)
            </dd>

            <dt>
                Arrival Time:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ARRIVALTIME)
            </dd>
            <dt>
                Train Status:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TRAIN.STATUS)
            </dd>

        </dl>
        <!--container for the edit button and back to list-->
        <div class="form-group">
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = Model.ROUTEID, idsch = Model.TRAINID })
            </p>
            <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index")
            </p>
        </div>
    </div>
</body>

WebAppAdmin/WebApp/Views/Schedules/Edit.cshtml
@model WebApp.Models.SCHEDULE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml";
    <style>
        /*where the css part of the page is */
        a { /*all the labels will have the following styling */
            color: black;
            background-color: transparent;
            text-decoration: none;
        }


            a:hover { /* styling when they are hovered*/
                color: red;
                background-color: transparent;
                text-decoration: underline;
            }

            a:active { /* styling when they weren't clicked before */
                color: yellow;
                background-color: transparent;
                text-decoration: underline;
            }
    </style>
    <body>
        <!--The title of the page with a user icon-->
        <h2><i class="fas fa-edit"></i> Edit Schedule</h2>

        <!--Creating a form with the user details-->
        @using (Html.BeginForm())
        {
            <!--the AntiForgeryToken for security-->
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" }) <!--summarize error messages in a specific place-->
            @Html.HiddenFor(model => model.ROUTEID) <!-- route ID is unique so it can't be changed-->

            @Html.HiddenFor(model => model.TRAINID) <!-- Train ID is unique so it can't be changed-->

            <div class="form-group">
                @Html.LabelFor(model => model.DEPARTURETIME, htmlAttributes: new { @class = "control-label col-md-2" }) <!--The departure time label-->
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DEPARTURETIME, new { htmlAttributes = new { @class = "form-control" } }) <!--The value of departure time-->
                    @Html.ValidationMessageFor(model => model.DEPARTURETIME, "", new { @class = "text-danger" }) <!--Displaying an error in the context if exists-->
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ARRIVALTIME, htmlAttributes: new { @class = "control-label col-md-2" }) <!--The arrival time label-->
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ARRIVALTIME, new { htmlAttributes = new { @class = "form-control" } }) <!--The value of arrival time-->
                    @Html.ValidationMessageFor(model => model.ARRIVALTIME, "", new { @class = "text-danger" }) <!--Displaying an error in the context if exists-->
                </div>
            </div>

            <!--Container with the Save and Back to list button-->
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" /> <!--Save button-->
                </div>
                <div style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-left: 10px;
                  margin-top: 10px;
                  margin:10px;
                  height:auto;
                  width: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
                    <i class="fas fa-arrow-left"></i> @Html.ActionLink("Back to List", "Index") <!--Button to go back to list-->
                </div>
            </div>
        </div>
        }
    </body>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

WebAppAdmin/WebApp/Views/Schedules/Index.cshtml
@model IEnumerable<WebApp.Models.SCHEDULE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResPagesLayout.cshtml"; // the layout of the page
}

<style>
    /*where the css part of the page is */
    a { /*all the labels will have the following styling */
        color: black;
        background-color: transparent;
        text-decoration: none;
    }


        a:hover { /* styling when they are hovered*/
            color: red;
            background-color: transparent;
            text-decoration: underline;
        }

        a:active { /* styling when they weren't clicked before */
            color: yellow;
            background-color: transparent;
            text-decoration: underline;
        }
</style>
<body>
    <!--The title of the page with a user icon-->
    <h2><i class="fas fa-calendar-alt"></i> Schedules</h2>

    <!--The search bar searching for Journey ID of the journey on the list on button click-->
    <p>
        @using (@Html.BeginForm("Index", "Schedules", FormMethod.Get))
        {
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "ROUTEID", true) <text>Route ID</text>
            @Html.TextBox("Search") <input type="submit" value="Search">
        }
    </p>

    <!--Create new user button which leads to the Create view of the journey with the appropriate design-->
    <a>
        <p style="
                  text-align:center;
                  background-color:#DCDCDC;
                  padding: 10px;
                  float:left;
                  margin-bottom:20px;
                  margin:10px;
                  width: auto;
                  height: auto;
                  border-radius: 0.2em; overflow: hidden;
                  position: relative;
                  box-shadow: 0px 1.5px 5px rgba(0,0,0,0.35)">
            <i class="fas fa-plus"></i> @Html.ActionLink("Create New", "Create")
        </p>
    </a>

    <!--Table where fields of the user are shown-->
    <table class="table">
        <tr>
            <th>
                Train ID <!--Train ID-->
            </th>
            <th>
                Route ID <!--Route ID-->
            </th>
            <th>
                Departure Time <!--Departure Time-->
            </th>
            <th>
                Arrival Time <!--Arrival Time-->
            </th>
            <th>
                Train Status <!--Train Status-->
            </th>
            <th></th>
        </tr>

        <!--For each field in the table for the user then the specific data are passed into the table-->
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TRAIN.TRAINID) <!--Train id will be displayed under the  train id field-->
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ROUTE.ROUTEID) <!--route id will be displayed under the  route id field-->
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DEPARTURETIME) <!--departure time id will be displayed under the  departure time field-->
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ARRIVALTIME) <!--Arrival time  will be displayed under the  arrival time id field-->
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TRAIN.STATUS) <!--train status  will be displayed under the  train status id field-->
                </td>
                <!--Edit, Details, Delete buttons at the end of the user details redirecting to their representative page-->
                <td>
                    <i class="fas fa-edit"></i> @Html.ActionLink("Edit", "Edit", new { id = item.ROUTEID, idsch = item.TRAINID }) |
                    <i class="fas fa-info-circle"></i> @Html.ActionLink("Details", "Details", new { id = item.ROUTEID, idsch = item.TRAINID }) |
                    <i class="fas fa-trash-alt"></i> @Html.ActionLink("Delete", "Delete", new { id = item.ROUTEID, idsch = item.TRAINID })
                </td>
            </tr>
        }

    </table>
</body>